<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameSP.BLL\GameSP.BLL.csproj" />
    <ProjectReference Include="..\GameSP.DAL\GameSP.DAL.csproj" />
    <ProjectReference Include="..\GameSP.Entities\GameSP.Entities.csproj" />
  </ItemGroup>

</Project>
